name = "tarot"
compatibility_date = "2025-11-01"
compatibility_flags = ["nodejs_compat"]

main = "dist/server/index.js"

[assets]
binding = "ASSETS"
directory = "dist/client"

[observability]
enabled = true
