name = "tarot"
compatibility_date = "2026-03-02"
compatibility_flags = ["nodejs_compat"]

main = "worker/index.ts"

[assets]
binding = "ASSETS"
directory = "dist/client"

[observability]
enabled = true
