name = "tarot"
compatibility_date = "2026-03-03"
compatibility_flags = ["nodejs_compat"]

main = ".vinext/worker.js"

[assets]
binding = "ASSETS"
directory = ".vinext/assets"

[observability]
enabled = true
